package ABMPersona;

import java.awt.Dimension;
import javax.swing.*;
import javax.swing.table.JTableHeader;

import Dominio.Administrativo;
import Dominio.Enfermeras;
import Dominio.Medicos;
import Dominio.Pacientes;

import java.awt.event.*;

/**
 *
 * @author vientosdepoder
 */
public class PersonaGUI extends JPanel {
	
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JSeparator jSeparatorV;
    private JSeparator jSeparatorH;
    private JComboBox jComboBox1;
    private JLabel jLabel1;
    private JTable jTable;
    private JTableHeader jTableHeader;

    /** Creates new form PersonaGUI */
    public PersonaGUI() {
    	
    	setName("panelPersona");
        setLayout(null);
		setSize(1000, 600);
		setPreferredSize(new Dimension(1000, 600));
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jComboBox1 = new JComboBox();
        jLabel1 = new JLabel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jSeparatorV = new JSeparator();
        jSeparatorH = new JSeparator();
        jTable = new JTable();
        jTableHeader = new JTableHeader();     

        jLabel1.setText("Categoria");
        jLabel1.setName("etiquetaCategoria");
        jLabel1.setBounds(25, 15, 75, 25);
        add(jLabel1);
        
        String[] categorias = { "Pacientes", "Administrativos", "Enfermeras", "Medicos" };
        jComboBox1.setModel(new DefaultComboBoxModel(categorias));
        jComboBox1.setName("comboBoxCategoria");
        jComboBox1.setBounds(100, 15, 130, 25);
        jComboBox1.setSelectedIndex(0);
        add(jComboBox1);
        
        jSeparatorV.setName("separadorVertical");
        jSeparatorV.setOrientation(SwingConstants.VERTICAL);
        jSeparatorV.setBounds(265, 15, 30,25);
        add(jSeparatorV);
        
        jSeparatorH.setName("separadorHorizontal");
        jSeparatorH.setOrientation(SwingConstants.HORIZONTAL);
        jSeparatorH.setBounds(10, 55, 980, 540);
        add(jSeparatorH);

        jButton1.setText("Alta");
        jButton1.setName("botonAlta");
        jButton1.setBounds(300, 15, 150, 25);
        add(jButton1);

        jButton2.setText("Baja");
        jButton2.setName("botonBaja");
        jButton2.setBounds(475, 15, 150, 25);
        add(jButton2);

        jButton3.setText("Modificar");
        jButton3.setName("botonModificar");
        jButton3.setBounds(650, 15, 150, 25);
        add(jButton3);

        jButton4.setText("Actualizar");
        jButton4.setName("botonActualizar");
        jButton4.setBounds(825, 15, 150, 25);
        add(jButton4);
        
        cargarTabla(jComboBox1.getSelectedIndex());
        
    }
    
    public void cargarTabla(int seleccion) {
    	jTable.setVisible(false);
    	jTableHeader.setVisible(false);
    	if (seleccion == 0) {
        	jTable = new Pacientes();
        } else if (seleccion == 1) {
        	jTable = new Administrativo();
        	repaint();
        } else if (seleccion == 2) {
        	jTable = new Enfermeras();
        } else if (seleccion == 3) {
        	jTable = new Medicos();
        }
        jTable.setName("tabla");
        jTable.setBounds(25, 95, 950, 490);
        jTableHeader = jTable.getTableHeader();
        jTableHeader.setBounds(25, 70, 950, 25);
        add(jTableHeader);
    	add(jTable);
    }

    
    public void addActionListener(ActionListener lis){
		jComboBox1.addActionListener(lis);
		jButton1.addActionListener(lis);
		jButton2.addActionListener(lis);
		jButton3.addActionListener(lis);
		jButton4.addActionListener(lis);
	}
    
}
